name: Publish Chart

on:
  push:
    branches:
      - main

env:
  HELM_VERSION_TO_INSTALL: 3.14.4 # version of HELM to install

jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest

      - name: login to gcr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }} --username ${{ github.repository_owner }} --password-stdin

      - name: package helm chart
        run: |
          helm package .

      - name: publish chart to gcr
        run: |
          helm push openwebrx-$(cat CHART_VERSION).tgz oci://ghcr.io/${{ github.repository_owner }}